#!/bin/bash

#SBATCH --job-name=SR_nanoplot_test
#SBATCH --partition=hpc
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=20g
#SBATCH --time=01:00:00
#SBATCH --output=/shared/home/<USERNAME>/slurm-%x-%j.out

#######################
# PREPARE ENVIRONMENT #
#######################

# load your bash profile (so you can use your conda install)
source $HOME/.bash_profile

# activate shared conda environment
conda activate /shared/conda/shared

cd /workhere/students_2023/group4/shortreads/nanoplot_report

# test flye
NanoPlot \
--threads 8 \
--fastq /workhere/students_2023/group4/all_longreads/allfiles.fastq.gz
--plots kde dot \
-o /workhere/students_2023/group4/shortreads/nanoplot_report

# deactivate conda environment
conda deactivate

