#!/bin/bash

#SBATCH --job-name=genovi
#SBATCH --partition=hpc
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=20g
#SBATCH --time=01:00:00
#SBATCH --output=/shared/home/mbyca6/slurm-%x-%j.out

#run genovi

#create a genovi environment (only need to do once)
#conda create -n genovi -c bioconda python=3.7 circos

#environment location: /shared/home/mbyca6/miniconda3/envs/genovi
conda activate genovi

#install package (only need to do once)
#pip3 install genovi

cd /workhere/students2023/group4/

#create output directorys:
#matt_data/genovi_test-temp/contig_1-matt_data/
#matt_data/genovi_test/matt_data/

#
genovi -i barcode10.gbk -o genovi_10 -s complete -bc white -cs ocean -te --size

#-i, genBank input file path.
#-o, output file name. Default: genovi.
#-cs, colour scheme: strong, autumn, dawn, blossom, paradise, neutral, blue, purple, soil, grayscale, velvet, pastel, ocean, wood, beach, desert, ice, island, forest, toxic, fire, spring.
#-s, --status. “complete” or “draft”. Complete genomes are drawn as separate circles for each contig/replicon.
#--size, displays the genome size of each independent circular representation.

#exit virtual environment:
deactivate
