#!/bin/bash

#SBATCH --job-name=genovi
#SBATCH --partition=hpc
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=20g
#SBATCH --time=01:00:00
#SBATCH --output=/shared/home/mbyca6/slurm-%x-%j.out

#run genovi

#create a genovi environment (only need to do once)
#conda create -n genovi -c bioconda python=3.7 circos

#environment location: /shared/home/mbyca6/miniconda3/envs/genovi
conda activate genovi

#install package (only need to do once)
#pip3 install genovi

cd /workhere/students2023/group4/

#create output directorys:
#matt_data/genovi_test-temp/contig_1-matt_data/
#matt_data/genovi_test/matt_data/

# run the genovi command
genovi \
-i barcode09.gbk \
-o genovi_09 \
-s complete \
-bc white \
-cs ocean \
-te \
--size


#exit virtual environment:
deactivate
